Link2defaults
ethereum/remix-ide pull request #3007
Opened 2021-02-22 05:30 UTC by ryestew

fixes https://github.com/ethereum/remix-project/issues/843

2021-02-22 05:33 UTC, ryestew commented
The PR updates the images of the new file explorer and updates instructions for installing remixd.

2021-02-23 16:13 UTC, Aniket-Engg requested changes

2021-02-23 16:13 UTC, Aniket-Engg commented on docs/file_explorer.md
> +The files explorer's **browser folder** has a sample project in it. The files stored in your browser's **browser storage**.
The files _are_ stored in...

2021-02-23 16:13 UTC, Aniket-Engg commented on docs/file_explorer.md
> +If, when you open Remix IDE, you do not see the sample project (like in the image above), they will appear when all the files in the File Explorer are erased or when the cache is cleared.
Choose one from `If, when`

2021-02-23 16:13 UTC, Aniket-Engg commented on docs/file_explorer.md
> +Right click on any file with a .js extension will gives the **run** option in the context menu.  The **run** shortcut is equivalent to getting the script file to be the active tab in the editor and t
will give

2021-03-02 15:27 UTC, LianaHus approved these changes

2021-03-02 15:28 UTC, merged