update loacations.md
ethereum/remix-ide pull request #3053
Opened 2022-01-11 03:08 UTC by ryestew

2022-01-11 07:44 UTC, ioedeveloper commented on docs/locations.md
> +Note: a plugin is called by its **name** in its profile.  There are three types of plugins - internally built plugins that are always loaded, internally built plugins that are loaded on demand and ex
Can we classify plugins into two categories `internal plugins and external plugins`, And then differentiate between internal plugins "always loaded" and internal plugins "loaded on demand"?

2022-01-12 05:54 UTC, Aniket-Engg requested changes

2022-01-12 05:54 UTC, Aniket-Engg commented on docs/locations.md
> +## Customize Remix with URLs with Parameters
I think title should be `Customize Remix with URL Parameters `

2022-01-12 05:54 UTC, Aniket-Engg commented on docs/locations.md
>  The following example contains the url parameter **activate** followed by **a list of plugins**. The last plugin will gain the focus.
One update can be: `followed by **a comma separated list of plugins**.`

2022-01-12 05:54 UTC, Aniket-Engg commented on docs/locations.md
> +Note: a plugin is called by its **name** in its profile.  There are three types of plugins - internally built plugins that are always loaded, internally built plugins that are loaded on demand and ex
May be we can categorise them as:

1. Native Plugins

  -  Mandatory or Default Plugins
  -  Optional Plugins

2. External Plugins

2022-01-12 05:54 UTC, Aniket-Engg commented on docs/locations.md
> +**fileManager**, **settings**, **settings**, **manager** (the plugin manager), and **udapp** (deploy & run)
**settings** is mentioned twice

2022-01-12 05:54 UTC, Aniket-Engg commented on docs/locations.md
> +**debugger**, **hardhat-provider**, **remixd**,**solidity**, **solidityStaticAnalysis**, **solidityUnitTesting**, and **vyper**
Not sure if `remixd` can be in this list

2022-01-12 05:54 UTC, Aniket-Engg commented on docs/locations.md
>  https://remix.ethereum.org/?#deactivate=udapp
I think this example should be updated as `udapp` cannot be deactivated

2022-01-12 05:54 UTC, Aniket-Engg commented on docs/locations.md
> +The `code` parameter takes an encoded base64 string and loads it the Editor as a .sol file and saves to the code-sample workspace of the File Explorer:
loads it **into** the Editor

2022-01-21 06:35 UTC, Aniket-Engg commented on docs/locations.md
> +1. **Native Manatory Plugins** that are always loaded (so you don't need to activate them in the url parameter **activate**). These include: **fileManager**, **settings**, **manager** (the plugin man
typo in `Mandatory`

2022-01-21 06:35 UTC, Aniket-Engg commented on docs/locations.md
> +1. **Native Manatory Plugins** that are always loaded (so you don't need to activate them in the url parameter **activate**). These include: **fileManager**, **settings**, **manager** (the plugin man
them using the url parameter **activate**

2022-01-21 06:35 UTC, Aniket-Engg commented on docs/locations.md
> +3. **External plugins** to get these plugins' names, please go to [https://github.com/ethereum/remix-plugins-directory/tree/master/plugins](https://github.com/ethereum/remix-plugins-directory/tree/ma
for the consistency, `p` in `plugins` should be in capital

2022-01-21 06:35 UTC, Aniket-Engg commented on docs/locations.md
> +The `url` parameter takes a URL, loads it into the Editor and saves to the code-sample workspace of the File Explorer:
saves into the

2022-01-24 06:55 UTC, Aniket-Engg approved these changes

2022-01-25 22:37 UTC, merged