Update gist example in the docs.
ethereum/remix-ide pull request #3125
Opened 2023-01-30 11:25 UTC by pranshu-taneja

Updated both the links as per their tasks. Now working perfectly.

**Load a GIST and have it be visible in the Editor** https://remix.ethereum.org/?#activate=solidity,fileManager&gist=0fe90e825327ef313c88aedfe66ec142&call=fileManager//open//gist-0fe90e825327ef313c88aedfe66ec142/gridMix4.sol 

**Load a GIST, have it be visible in the Editor & load a list of plugins** https://remix.ethereum.org/?#activate=solidity,pluginManager&gist=0fe90e825327ef313c88aedfe66ec142&call=fileManager//open//gist-0fe90e825327ef313c88aedfe66ec142/gridMix4.sol

2023-01-30 11:32 UTC, pranshu-taneja commented
Here is the issue link posted on remix project GitHub repository:
https://github.com/ethereum/remix-project/issues/951

2023-01-30 17:15 UTC, Aniket-Engg requested changes

2023-01-30 17:15 UTC, Aniket-Engg commented on docs/locations.md
> +https://remix.ethereum.org/?#activate=solidity,pluginManager&gist=0fe90e825327ef313c88aedfe66ec142&call=fileManager//open//gist-0fe90e825327ef313c88aedfe66ec142/gridMix4.sol
`pluginManager ` is loaded by default. You can revert this change

2023-01-30 18:03 UTC, pranshu-taneja reviewed
The change is on **Line 164** not on **Line 159** (mistakenly typed)

2023-01-31 07:42 UTC, Aniket-Engg approved these changes

2023-01-31 07:42 UTC, Aniket-Engg commented
Thanks @pranshu-taneja !!!

2023-01-31 07:42 UTC, merged